import assert from 'node:assert/strict'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser = await chromium.launch({ channel: 'chrome', headless: true })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5173/')
  const text = page.locator('.app-announcement .text-gradient')
  await text.scrollIntoViewIfNeeded()
  const position = () => text.evaluate(el => getComputedStyle(el).backgroundPosition)
  const first = await position()
  await page.waitForTimeout(500)
  assert.notEqual(await position(), first, 'Gradient moves')
  await page.getByRole('button', { name: 'Pause text animation' }).click()
  await page.waitForTimeout(100)
  const paused = await position()
  await page.waitForTimeout(400)
  assert.equal(await position(), paused, 'Pause freezes the gradient')
  await page.getByRole('button', { name: 'Resume text animation' }).click()
  await page.waitForTimeout(400)
  assert.notEqual(await position(), paused, 'Resume restarts the gradient')
  await page.screenshot({ path: 'output/text-gradient-desktop.png' })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.waitForTimeout(150)
  const reduced = await position()
  await page.waitForTimeout(400)
  assert.equal(await position(), reduced, 'Reduced motion remains still')
  await page.setViewportSize({ width: 390, height: 844 })
  await text.scrollIntoViewIfNeeded()
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
  await page.screenshot({ path: 'output/text-gradient-mobile.png' })
  await page.emulateMedia({ forcedColors: 'active' })
  assert.notEqual(await text.evaluate(el => getComputedStyle(el).color), 'rgba(0, 0, 0, 0)', 'High contrast text stays visible')
  console.log('Text gradients: movement, pause/resume, reduced motion, mobile and forced colors passed.')
} finally { await browser.close() }
