import BrandLogo from '../components/BrandLogo'
import { Link } from 'react-router-dom'
import { ArrowRight } from 'lucide-react'

const swatches = [['Ocean', '--background', '#15232c'], ['Deep water', '--bg-deep', '#101a22'], ['Foam', '--foreground', '#f3f7f5'], ['Sea glass / action', '--action', '#6ee8bd'], ['Logo teal', '--teal', '#00c9bb'], ['Logo green', '--green', '#00e68b'], ['Logo blue', '--blue', '#00a5eb'], ['Supporting text', '--muted-foreground', '#bacbd0']]

export default function StyleGuidePage() {
  return <div className="min-h-screen pt-32 style-guide"><div className="wrap" style={{paddingBottom:100}}>
    <h1 className="display">The Maniacs<br />style guide.</h1><p className="section-deck">An ocean world. A steady hand. A clear next move.</p>
    <section><h2 className="headline">Keep the real mark.</h2><div className="specimen" style={{background:'#242730'}}><BrandLogo /></div><p className="spec">Use the original logo file. Preserve the wave, lettering and teal-to-green-to-blue palette. Match its charcoal background when placing it in navigation. Use the shared horizontal BrandLogo: wave first, then Career Maniacs on one line. CSS crops preserve the original artwork. Career Maniacs and GTM Maniacs remain distinct brands.</p></section>
    <section><h2 className="headline">Color comes from the water.</h2><div className="swatches">{swatches.map(([name,token,hex])=><div key={token}><div className="swatch-color" style={{background:`var(${token})`}} /><strong>{name}</strong><p className="spec">{token}<br />{hex}</p></div>)}</div><p className="spec">Sea glass is the action color. Logo colors support the identity. Sunrise warmth belongs in the imagery, not the primary button. White and muted copy sit on opaque ocean surfaces where reading takes priority.</p></section>
    <section><h2 className="headline">One type family. Room to breathe.</h2><div className="specimen"><p className="display">Stop blending in.</p><p className="headline" style={{marginTop:30}}>Tell the story.</p><p className="headline-sm" style={{marginTop:24}}>Ask the better question.</p><p className="section-deck">Archivo carries the whole site. Wide, confident headlines. Readable body copy. No decorative second voice.</p></div><p className="spec">Self-hosted Archivo variable, SIL Open Font License. Display up to 96px, section titles 32–52px, body 16–20px. Headline tracking no tighter than −0.035em. Body line height 1.65–1.8. Keep prose below 75 characters per line.</p></section>
    <section><h2 className="headline">Say what happens next.</h2><div className="specimen actions"><Link to="/contact#book" className="btn-primary">Talk to Jeff <ArrowRight size={18} aria-hidden="true" /></Link><Link to="/services" className="btn-ghost">Explore coaching</Link><Link to="/testimonials" className="text-link">Read client stories <ArrowRight size={18} aria-hidden="true" /></Link></div><p className="spec">Talk to Jeff opens an inquiry form. Send request submits it; it does not book an appointment. Current-client scheduling uses a real Calendly link. Keep visible focus, native labels, disabled and error states. Buttons have at least a 46px touch height.</p></section>
    <section><h2 className="headline">The page has a story.</h2><img src="/maniac-wave.webp" alt="Temporary illustrative wave for the Maniac Method chapter" width="1536" height="1024" style={{width:'100%',maxHeight:420,objectFit:'cover',borderRadius:12,marginTop:30}} /><p className="spec">Begin with a calm sunrise still. Show the wave behind the five Maniac Method modules: Research, Outbound, Discovery, Objection Handling and Close. End with brighter ocean water. Use narrow ocean-image borders at selected section boundaries. No fixed ocean backdrop, glass panels or scroll traps.</p></section>
    <section><h2 className="headline">Write like Jeff.</h2><div className="specimen"><p className="headline-sm">Bring the role. Bring the hard question.</p><p className="section-deck">We’ll decide whether this is the right fit.</p></div><p className="spec">Bold, edgy, specific and human. A Maniac prepares relentlessly, stays curious and commits fully. Connect the surfing and kitesurfing story to that attitude. Start with the point. Use the actual problem, decision or next step. Skip “unlock your potential,” “seamless,” “leverage” and generic motivational copy. Preserve client quotations exactly. Label illustrative examples. MIT degree and guaranteed call takeaways are retained at Jeff’s explicit direction; don’t turn them into employment guarantees.</p></section>
    <section><h2 className="headline">Build with what’s here.</h2><p className="spec">Use App.css tokens and the existing React, Router, Motion and Lucide stack. Desktop content width: 1184px. Mobile gutters: 20px. Surface radius: 12px. Use spacing before adding boxes. This page uses the same live tokens and components as the website.</p><Link to="/" className="text-link">Return to Career Maniacs <ArrowRight size={18} aria-hidden="true" /></Link></section>
  </div></div>
}
